### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by Shreif-Shouman** [tfeldmann/gpsdclient#2]
Hello,
I'm trying to run the following script:

from gpsdclient import GPSDClient

client = GPSDClient(host="127.0.0.1")
for result in client.json_stream():
    print(result)

But it gives me always the error 

    714             if source_address:
    715                 sock.bind(source_address)
    716             sock.connect(sa)
    717             # Break explicitly a reference cycle
    718             err = None

ConnectionRefusedError: [Errno 61] Connection refused

I try to change the host to '0.0.0.0' but still not working and I do not know how to solve it ???!!!
Any hints for that!!

**Comment by tfeldmann** [comment]
Is gpsd running in the background?

**Comment by Shreif-Shouman** [comment]
well, I think yes it's running in the background, because if I print (client) I get back:
<GPSDClient(host=127.0.0.1, port=2947)>

**Comment by tfeldmann** [comment]
Did you install gpsd on your system? Ehat is the output of systemctl status gpsd (if you are on linux)?

**Comment by tfeldmann** [comment]
Closing this as I suspect gpsd was not installed
